import "./globals.css";
import Header from "@/Header";
import localFont from "next/font/local";

const yourFont = localFont({
  src: "../public/fonts/vitroInspire.otf", // 폰트 파일 경로
  display: "swap",
  variable: "--font-your-font", // CSS 변수 이름 설정
});

export const metadata = {
  title: "Itescape",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`bg-[#3C465C] ${yourFont.variable}`}>
      <body>
        <div className="bg-[#D9D9D9] px-10 border-b">
          <Header />
        </div>
        <main className="bg-[#3C465C]">{children}</main>
      </body>
    </html>
  );
}
