import Link from "next/link";
import "./globals.css";
import Header from "@/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="px-10  border-b">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
